version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - asdf global python 3.9.22
    - pip install mkdocs
    - cd docs
    - mkdocs build --config-file mkdocs.yml --site-dir $READTHEDOCS_OUTPUT/html